title: AZADRG Blog
description: Tech notes & field logs
url: "https://azadrg.cloud"
plugins:
  - jekyll-feed

feed:
  path: blog/feed.xml
future: true

permalink: /blog/:year/:month/:day/:title.html
plugins:
  - jekyll-feed
feed:
  path: blog/feed.xml
